// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiGames.Data;

#nullable disable

namespace WikiGames.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220512182040_generoJuegos")]
    partial class generoJuegos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DesarrolladorJuego", b =>
                {
                    b.Property<int>("DesarrolladoraDesarrolladorId")
                        .HasColumnType("int");

                    b.Property<int>("JuegosJuegoId")
                        .HasColumnType("int");

                    b.HasKey("DesarrolladoraDesarrolladorId", "JuegosJuegoId");

                    b.HasIndex("JuegosJuegoId");

                    b.ToTable("DesarrolladorJuego");
                });

            modelBuilder.Entity("GeneroJuego", b =>
                {
                    b.Property<int>("GenerosGeneroId")
                        .HasColumnType("int");

                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.HasKey("GenerosGeneroId", "JuegoId");

                    b.HasIndex("JuegoId");

                    b.ToTable("GeneroJuego");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Consola", b =>
                {
                    b.Property<int>("ConsolaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsolaId"), 1L, 1);

                    b.Property<string>("ConsolaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("date");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.HasKey("ConsolaId");

                    b.HasIndex("MarcaId")
                        .IsUnique();

                    b.ToTable("Consolas");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Desarrollador", b =>
                {
                    b.Property<int>("DesarrolladorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesarrolladorId"), 1L, 1);

                    b.Property<DateTime?>("Cierre")
                        .HasColumnType("date");

                    b.Property<DateTime>("Creacion")
                        .HasColumnType("date");

                    b.Property<string>("DesarrolladorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DesarrolladorId");

                    b.ToTable("Desarrolladores");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Juego", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JuegoId"), 1L, 1);

                    b.Property<DateTime>("FechaLanzamientoOficial")
                        .HasColumnType("date");

                    b.Property<string>("JuegoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("JuegoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JuegoId");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.JuegoConsola", b =>
                {
                    b.Property<int>("JuegoId")
                        .HasColumnType("int");

                    b.Property<int>("ConsolaId")
                        .HasColumnType("int");

                    b.Property<int>("CopiasVendidas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("date");

                    b.HasKey("JuegoId", "ConsolaId");

                    b.HasIndex("ConsolaId");

                    b.ToTable("JuegosConsolas");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"), 1L, 1);

                    b.Property<string>("MarcaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("DesarrolladorJuego", b =>
                {
                    b.HasOne("WikiGames.Models.Entities.Desarrollador", null)
                        .WithMany()
                        .HasForeignKey("DesarrolladoraDesarrolladorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiGames.Models.Entities.Juego", null)
                        .WithMany()
                        .HasForeignKey("JuegosJuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneroJuego", b =>
                {
                    b.HasOne("WikiGames.Models.Entities.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosGeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiGames.Models.Entities.Juego", null)
                        .WithMany()
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Consola", b =>
                {
                    b.HasOne("WikiGames.Models.Entities.Marca", "Marca")
                        .WithOne("Consola")
                        .HasForeignKey("WikiGames.Models.Entities.Consola", "MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.JuegoConsola", b =>
                {
                    b.HasOne("WikiGames.Models.Entities.Consola", "Consola")
                        .WithMany("JuegoConsola")
                        .HasForeignKey("ConsolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiGames.Models.Entities.Juego", "Juego")
                        .WithMany("JuegoConsola")
                        .HasForeignKey("JuegoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consola");

                    b.Navigation("Juego");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Consola", b =>
                {
                    b.Navigation("JuegoConsola");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Juego", b =>
                {
                    b.Navigation("JuegoConsola");
                });

            modelBuilder.Entity("WikiGames.Models.Entities.Marca", b =>
                {
                    b.Navigation("Consola");
                });
#pragma warning restore 612, 618
        }
    }
}
